@url=http://127.0.0.1:3010
@json=Content-Type: application/json


### 注册

post {{url}}/login/register
{{json}}

{
    "username": "亲爱的安德烈123",
    "password": "123456"
}

### login
post {{url}}/api/login
{{json}}

{
    "username": "admin",
    "password": "123456"
}


### signFund
post {{url}}/api/signFund
{{json}}

{
    "userId": 123,
    "pageSize": 20,
    "pageNo": 1
}

